permissions:
    - 'CreateDummyUser'
    - 'CrudStuff'


endpoints:

      # ----- Get Stuff
      /api/stuff/load:
          method: 'GET'
          authentication-required: true
          required-permission: null
          accounting:
            exclude-from-request: []
            exclude-from-response: []


      /api/stuff/save:
          method: 'POST'
          authentication-required: true
          required-permission: 'CrudStuff'
          accounting:
            exclude-from-request: []
            exclude-from-response: []
